import Head from 'next/head'
import Banner from '../components/Banner/Banner'
import Card from '../components/Card/Card'
import CardContainer from '../components/Card/CardContainer'
import NavBar from '../components/NavBar/NavBar'
import { getVideos, getPopularVideos } from '../lib/videos'

import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const disneyVideos = await getVideos('disney trailer')
  const productivityVideos = await getVideos('productivity')
  const travelVideos = await getVideos('travel')
  const popularVideos = await getPopularVideos('')

  return { props: { disneyVideos, productivityVideos, travelVideos, popularVideos } }
}
// const key = AIzaSyAjJ4qNerU5yPdMYYGx3IXFOdsr8VkUTV4
export default function Home({
  disneyVideos,
  productivityVideos,
  travelVideos,
  popularVideos
}) {
  console.log({ disneyVideos })

  const test = [
    {
      imgUrl: '/static/ridge.jpeg'
    },
    {
      imgUrl: '/static/ridge.jpeg'
    },
    {
      imgUrl: '/static/ridge.jpeg'
    },
    {
      imgUrl: '/static/ridge.jpeg'
    }
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>My youtube</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <h1>my youtube</h1> */}
      <div className={styles.main}>
        <NavBar />
        <Banner title={'ridge'} subTitle={'war'} imgUrl={'/static/ridge.jpeg'} />
        <div className={styles.cardContainer}>
          <CardContainer title={'disney'} videos={disneyVideos} size={'large'} />
          <CardContainer title={'travel'} videos={travelVideos} size={'small'} />
          <CardContainer
            title={'Productivity'}
            videos={productivityVideos}
            size={'medium'}
          />
          <CardContainer title={'Popular'} videos={popularVideos} size={'small'} />
        </div>
      </div>
    </div>
  )
}
